### ISSUE TITLE
_p9k_worker_stop:zle:4: No handler installed for fd 1

### ISSUE THREAD

**Issue by tomahawk-pilot** [romkatv/powerlevel10k#1554]
_p9k_worker_stop:5: failed to close file descriptor 13: bad file descriptor
latest version of code
os: ubuntu 20.04
shell: ohmyzsh

**Comment by romkatv** [comment]
Can you reproduce this if you disable all plugins in your zshrc?

**Comment by Glastis** [comment]
Had this but, commenting `git` plugin solved the issue.

```shell
plugins=(zsh-z git)
```
to 
```shell
plugins=(zsh-z `#git`)
```

**Comment by CleoMenezesJr** [comment]
Same here!

**Comment by saxena07** [comment]
gitstatus_stop_p9k_:zle:41: No handler installed for fd 14
gitstatus_stop_p9k_:49: failed to close file descriptor 14: bad file descriptor
how to solve this ?

**Comment by romkatv** [comment]
@saxena07 This is probably another instance of the bug that https://github.com/zsh-users/zsh-autosuggestions/pull/753 should fix. You can verify this by adding the following line at the very bottom of `~/.zshrc`:

```zsh
unset ZSH_AUTOSUGGEST_USE_ASYNC
```

**Comment by ericfreese** [comment]
I have merged [a commit to zsh-autosuggestions `develop` branch](https://github.com/zsh-users/zsh-autosuggestions/pull/630). If folks are seeing this while also running zsh-autosuggestions, please try the develop branch and see if it solves the problem.

**Comment by hrokr** [comment]
I just had this issue today

```
gitstatus_stop_p9k_:zle:41: No handler installed for fd 14
gitstatus_stop_p9k_:49: failed to close file descriptor 14: bad file descriptor 
```
So, some aspect must still not be resolved. That said, `unset ZSH_AUTOSUGGEST_USE_ASYNC` seems to resolve it just fine.

**Comment by romkatv** [comment]
https://github.com/zsh-users/zsh-autosuggestions/pull/753 hasn't been merged. The process has stalled.
