### ISSUE TITLE
Prompt hangs forever

### ISSUE THREAD

**Issue by caddac** [romkatv/powerlevel10k#156]
Sometimes my prompt hangs forever. I placed `set -x` at the top of a script that tends to cause this to happen and found what appears to be an infinite loop running, printing continuously:
```
+_p9k_vcs_status_for_dir:3> _P9K_RETVAL=''
+_p9k_vcs_status_for_dir:4> [[ -n '' ]]
+_p9k_vcs_status_for_dir:5> [[ . == / ]]
+_p9k_vcs_status_for_dir:6> dir=.
+_p9k_vcs_status_for_dir:2> true
+_p9k_vcs_status_for_dir:3> _P9K_RETVAL=''
+_p9k_vcs_status_for_dir:4> [[ -n '' ]]
+_p9k_vcs_status_for_dir:5> [[ . == / ]]
+_p9k_vcs_status_for_dir:6> dir=.
+_p9k_vcs_status_for_dir:2> true
```

This doesn't happen with `powerlevel9k`. 

Relevant `.zshrc` config:
```
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git colored-man colorize github virtualenv pip python brew osx zsh-syntax-highlighting docker aws)

source $ZSH/oh-my-zsh.sh

POWERLEVEL9K_DIR_FOREGROUND='white'
POWERLEVEL9K_DIR_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='white'
POWERLEVEL9K_DIR_ETC_FOREGROUND='white'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'

POWERLEVEL9K_DIR_BACKGROUND='grey19'
POWERLEVEL9K_DIR_HOME_BACKGROUND='grey19'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='grey19'
POWERLEVEL9K_DIR_ETC_BACKGROUND='grey19'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='grey19'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
```

I'm not sure if this is a bug or a mis-configuration on my part. Do you have some guidance on how I can troubleshoot this issue?

**Comment by romkatv** [comment]
This could happen if some code in your shell changes `PWD`. I've committed a fix so that p10k doesn't break in such cases.

Please update powerlevel10k and try again. Let me know whether it fixes the issue for you.

**Comment by caddac** [comment]
I updated, and now at the end of my script I'm getting `gitstatus_query:5: PWD: parameter not set` and prompt still hangs. 

A couple interesting observations. 

With `set -x` on I can see its no longer printing forever in a loop. Here are the last few lines of the debug output:
```
+_p9k_vcs_status_for_dir:4> return 0
+_p9k_vcs_gitstatus:15> true
+_p9k_vcs_gitstatus:16> case  ()
+_p9k_vcs_gitstatus:17> [[ /Users/dave.cavaletto/source/AWSInfrastructure/s3 == / ]]
+_p9k_vcs_gitstatus:17> dir=/Users/dave.cavaletto/source/AWSInfrastructure
+_p9k_vcs_gitstatus:15> true
+_p9k_vcs_gitstatus:16> case  ()
+_p9k_vcs_gitstatus:17> [[ /Users/dave.cavaletto/source/AWSInfrastructure == / ]]
+_p9k_vcs_gitstatus:17> dir=/Users/dave.cavaletto/source
+_p9k_vcs_gitstatus:15> true
+_p9k_vcs_gitstatus:16> case  ()
+_p9k_vcs_gitstatus:17> [[ /Users/dave.cavaletto/source == / ]]
+_p9k_vcs_gitstatus:17> dir=/Users/dave.cavaletto
+_p9k_vcs_gitstatus:15> true
+_p9k_vcs_gitstatus:16> case  ()
+_p9k_vcs_gitstatus:17> [[ /Users/dave.cavaletto == / ]]
+_p9k_vcs_gitstatus:17> dir=/Users
+_p9k_vcs_gitstatus:15> true
+_p9k_vcs_gitstatus:16> case  ()
+_p9k_vcs_gitstatus:17> [[ /Users == / ]]
+_p9k_vcs_gitstatus:17> dir=/
+_p9k_vcs_gitstatus:15> true
+_p9k_vcs_gitstatus:16> case  ()
+_p9k_vcs_gitstatus:17> [[ / == / ]]
+_p9k_vcs_gitstatus:17> break
+_p9k_vcs_gitstatus:22> dir=/Users/dave.cavaletto/source/AWSInfrastructure/s3
+_p9k_vcs_gitstatus:24> gitstatus_query -d /Users/dave.cavaletto/source/AWSInfrastructure/s3 -t 0.0500000000 -c '_p9k_vcs_resume 1' POWERLEVEL9K
+gitstatus_query:1> emulate -L zsh
+gitstatus_query:2> setopt err_return no_unset
+gitstatus_query:4> local opt
gitstatus_query:5: PWD: parameter not set
```


Here is the meat of this script I'm running:
```
# removed code that set variables and handles args

aws sts assume-role --role-arn $ROLE_ARN --output text --role-session-name $AWS_USER-session  --output text  \
  | grep -v ASSUMEDROLEUSER \
  | awk '{printf("export AWS_REGION=\"us-east-1\"\nexport AWS_ACCESS_KEY_ID=\"%s\"\nexport AWS_SECRET_ACCESS_KEY=\"%s\"\nexport AWS_SESSION_TOKEN=\"%s\"\nexport AWS_SECURITY_TOKEN=\"%s\"\n",$2,$4,$5,$5)}' | tee ~/.bashrc.aws
for x in `env | grep -v AWS_DEFAULT_PROFILE \
              | grep -v AWS_USER   | grep AWS | cut -d\= -f 1`;
    do unset $x;
  
done

# source the file
. ~/.bashrc.aws
```
the script returns:
```
export AWS_REGION="us-east-1"
export AWS_ACCESS_KEY_ID=a_value
export AWS_SECRET_ACCESS_KEY=a_value
export AWS_SESSION_TOKEN=a_value
export AWS_SECURITY_TOKEN=a_value
```

The script is called 'get-role.sh' and is run like `source get-role some_role`.

I mention all of this because if don't `source` the script output (just run `get-role some_role`) then the script works and the prompt return normally.

**Comment by romkatv** [comment]
> ```zsh
> for x in `env | grep -v AWS_DEFAULT_PROFILE \
>               | grep -v AWS_USER   | grep AWS | cut -d\= -f 1`;
>     do unset $x;
> done
> ```

This code unsets all variables with `AWS` in their names **or their values**. Your current directory happens to have `AWS` in it, so `PWD` gets unset.

I've changed gitstatus so that it survives such brutality. If you update powerlevel10k, it should no longer print errors or hang when you execute your script while in a directory with `AWS` in it. However, it's a very good idea to fix the script. Lots of code breaks if you unset `PWD`, and it's hard to predict other issues this will cause in the future (who knows which important variables might have `AWS` in their names or values?). Unsetting variables with a wide pattern is risky and dangerous.

If the goal is to unset all variables that start with `AWS_` except for `AWS_DEFAULT_PROFILE` and `AWS_USER`, you can do it like this:

```zsh
setopt extended_glob
unset -m 'AWS_*~(AWS_DEFAULT_PROFILE|AWS_USER)'
```

**Comment by caddac** [comment]
awesome. Everything works awesome! Thanks so much for the feedback on my script.
