### ISSUE TITLE
Kitty output of the last command in a pager using p10k doesn't work well

### ISSUE THREAD

**Issue by aryklein** [romkatv/powerlevel10k#1749]
When using p10k and Kitty, the output of the last command in a pager using `ctrl+shift+g` doesn't' work well: output from commands like `ls` or `cat some-file` are empty, while output from commands like `top` or `find /` works fine.

If you execute `top` and then `ls`, you will see in the pager the `top` output.

I tried to remove all content from my `.zshrc` and only let the p10k stuff but didn't solve the issue:

```bash
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```
This is my [.p10k.zsh](https://github.com/aryklein/dotfiles/blob/main/zsh/.p10k.zsh) file.

If I comment out the p10k stuff, it works fine.

```bash
~ ❯ kitty --version
kitty 0.24.1 created by Kovid Goyal
```

This is my [kitty.conf ](https://github.com/aryklein/dotfiles/blob/main/kitty/.config/kitty/kitty.conf)

**Comment by aryklein** [comment]
btw, I'm using Arch Linux up-to-date

**Comment by kovasap** [comment]
I have the same problem: https://github.com/kovidgoyal/kitty/issues/4604

**Comment by romkatv** [comment]
Oh god, I've introduced a bug in shell integration code but it was completely invisible to me because I'm using zsh4humans. It should be fixed now. Please update powerlevel10k and let me know whether it works for you.

**Comment by aryklein** [comment]
Thanks so much @romkatv. Now it works.
I will notify here as well: https://github.com/kovidgoyal/kitty/issues/4536

**Comment by kovasap** [comment]
Hmmm, this still doesn't work for me on the latest powerlevel10k version.  Any tips for tracking down why?

**Comment by aryklein** [comment]
Did you clone it from the `master` branch? keep in mind that the commit was merged 2hrs ago.

**Comment by kovasap** [comment]
```
> git log   
commit 8a676a9157d2b0e00e88d06456ac7317f11c0317 (HEAD -> master, origin/master, origin/HEAD)
Author: Roman Perepelitsa <roman.perepelitsa@gmail.com>
Date:   Tue Feb 1 20:39:00 2022 +0100

    fix shell integration with kitty
```

**Comment by romkatv** [comment]
@kovasap Please post everything that will allow me to reproduce this: all relevant configs (make sure they are as small as possible) and the description of all steps that are necessary to demonstrate the issue.

**Comment by kovasap** [comment]
My `.zshrc` is at https://github.com/kovasap/dotfiles/blob/master/.zshrc and I'm starting kitty with no config like `kitty --config=NONE -o 'map ctrl+shift+k show_last_command_output'`.  Then, running `ls` and pressing `ctrl+shift+k` leads to no output in the `less` that pops up.

Sorry I don't have time to par down my `.zshrc` right now.  No worries if it makes it too hard to debug.

**Comment by romkatv** [comment]
@kovasap Try this:

1. Run:
```zsh
() {
  emulate -L zsh -o err_return -o xtrace -o extended_glob
  command mkdir -p -- ~/.zsh-backup
  local rcs=(~/{.zshenv,.zlogin,.zlogout,.zprofile,.zshrc}{,.zwc}(N))
  (( $#rcs )) && command mv -f -- $rcs ~/.zsh-backup
  if [[ -n ~/powerlevel10k(#qNF) ]]; then
    command git -C ~/powerlevel10k pull
  else
    command git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
  fi
  >~/.zshrc <<<$'source ~/powerlevel10k/powerlevel10k.zsh-theme\nPOWERLEVEL9K_TERM_SHELL_INTEGRATION=true' 
}
```
2. Run:
  ```zsh
  kitty --config=NONE -o 'map ctrl+shift+k show_last_command_output'
  ```
4. Run in the new terminal:
  ```zsh
  ls
  ```
5. Press in the new terminal: <kbd>Ctrl-Shift-K</kbd>

Does this display the output of `less` in pager?

**Comment by kovasap** [comment]
That works as expected for me: I can see the output of `ls` in my pager.  Does this suggest that there is something with my p10k config that I would need to tweak for this to work?

**Comment by romkatv** [comment]
@kovasap I don't know what it suggests. It's now up to you to figure out what in your setup is crucial to trigger the bug.

**Comment by kovasap** [comment]
For future readers, it looks like removing this line from my `.zshrc` fixed the problem and didn't seem to have any other affects on my p10k usage:
```
ZSH_THEME="powerlevel10k/powerlevel10k"
```

**Comment by romkatv** [comment]
> For future readers, it looks like removing this line from my `.zshrc` fixed the problem and didn't seem to have any other affects on my p10k usage:
> 
> ```
> ZSH_THEME="powerlevel10k/powerlevel10k"
> ```

Aha, so you have two versions of powerlevel10k installed and was loading both of them. The one within omz is old, so it doesn't work with the new kitty.

**Comment by kovasap** [comment]
Oh that makes sense!
