### ISSUE TITLE
Showing incorrect namespace based on current showing in `kb config get-contexts`

### ISSUE THREAD

**Issue by robbyki** [romkatv/powerlevel10k#1767]
I'm close to getting my prompt the way I want but despite having the following, it shows `default` ns in my prompt even though running `kb config get-contexts` shows the current ns to be `openshift-image-registry` in the `NAMESPACE` column. Not sure what I'm missing.

```
❯ echo $POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION
$P9K_KUBECONTEXT_NAME:$P9K_KUBECONTEXT_NAMESPACE
```

Here in how my prompt looks:
![image](https://user-images.githubusercontent.com/1027357/153710263-79374c7b-2432-48fe-bfb9-da7d264fd8e0.png)

**Comment by robbyki** [comment]
sure. this command also returns the correct ns: `kubectl config view --minify --output 'jsonpath={..namespace}'; echo`

```
apiVersion: v1
clusters:
- cluster:
    server: https://c115-e.us-south.containers.cloud.ibm.com:31589
  name: c115-e-us-south-containers-cloud-ibm-com:31589
- cluster:
    server: https://c115-e.us-south.containers.cloud.ibm.com:31589
  name: test-cluster-rk/c80phsgd0he7fpn9eov0
contexts:
- context:
    cluster: c115-e-us-south-containers-cloud-ibm-com:31589
    namespace: default
    user: IAM#<user>/c115-e-us-south-containers-cloud-ibm-com:31589
  name: default/c115-e-us-south-containers-cloud-ibm-com:31589/IAM#<user>
- context:
    cluster: c115-e-us-south-containers-cloud-ibm-com:31589
    namespace: openshift-image-registry
    user: IAM#r<user>/c115-e-us-south-containers-cloud-ibm-com:31589
  name: helloworld/c115-e-us-south-containers-cloud-ibm-com:31589/IAM#<user>
- context:
    cluster: test-cluster-rk/c80phsgd0he7fpn9eov0
    namespace: default
    user: admin/c80phsgd0he7fpn9eov0
  name: test-cluster-rk/c80phsgd0he7fpn9eov0/admin
current-context: helloworld/c115-e-us-south-containers-cloud-ibm-com:31589/IAM#<user>
kind: Config
```

**Comment by romkatv** [comment]
Thanks. Should be fixed now. Please update and let me know whether it works.

**Comment by robbyki** [comment]
Thanks. I have 5fe28f0a010acd251c25a5bd62dfd8002c37f46c now but still showing as default.
![image](https://user-images.githubusercontent.com/1027357/153858150-055c72a5-9db0-41ff-8165-bddc4b14ff60.png)

**Comment by robbyki** [comment]
sorry. spoke to soon. seems to be good now: thank you. 
![image](https://user-images.githubusercontent.com/1027357/153858739-87190509-3315-4f61-8794-c118e46f2354.png)

**Comment by romkatv** [comment]
Thanks for verifying.
