### ISSUE TITLE
Nodenv version does not auto update prompt

### ISSUE THREAD

**Issue by fdsa789** [romkatv/powerlevel10k#2268]
After updating node version from nodenv - ex) `nodenv global 18.2.0` , it doesn't update version number in prompt. Are there any other configs for auto updating version number?

It also  doesn't update even restarting shell or terminal - I use zsh and iTerm. 

Below is my current config:

```shell
  ##########[ nodenv: node.js version from nodenv (https://github.com/nodenv/nodenv) ]##########
  # Nodenv color.
  typeset -g POWERLEVEL9K_NODENV_FOREGROUND=2
  typeset -g POWERLEVEL9K_NODENV_BACKGROUND=0
  # Hide node version if it doesn't come from one of these sources.
  typeset -g POWERLEVEL9K_NODENV_SOURCES=(shell local global)
  # If set to false, hide node version if it's the same as global:
  # $(nodenv version-name) == $(nodenv global).
  typeset -g POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW=false
  # If set to false, hide node version if it's equal to "system".
  typeset -g POWERLEVEL9K_NODENV_SHOW_SYSTEM=true
  # Custom icon.
  # typeset -g POWERLEVEL9K_NODENV_VISUAL_IDENTIFIER_EXPANSION='⭐'
```

**Comment by romkatv** [comment]
Please run the following command and post a screenshot that shows the command, its output, and prompt.

```zsh
nodenv version-name; print '==='; nodenv global
```

**Comment by fdsa789** [comment]
@romkatv Here is the screenshot.

![screenshot](https://user-images.githubusercontent.com/107389031/232348124-4e95a6dc-4a82-406f-9474-0b48c3c53078.png)

**Comment by romkatv** [comment]
Are you sure it's `nodenv` in prompt? Could you run this?

```zsh
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(nodenv); p10k reload
```

If after running this command `18.12.0` disappears from right prompt, it means it wasn't `nodenv` to begin with. Try to figure out which prompt segment that is. You can do that by commending out elements of `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` in `~/.p10k.zsh` one by one.

**Comment by fdsa789** [comment]
@romkatv 

Thanks! Just realized that prompt was coming from `node_version`.

There is node version prompt when there is `.node-version` file in my project, but is there way that is detects node project and prompts node version from nodenv global or local `.node-version`? Is there something I'm missing?

My `nodenv` config in p10k file:

```zsh
  typeset -g POWERLEVEL9K_NODENV_FOREGROUND=2
  typeset -g POWERLEVEL9K_NODENV_BACKGROUND=0
  # Hide node version if it doesn't come from one of these sources.
  typeset -g POWERLEVEL9K_NODENV_SOURCES=(shell local global)
  # If set to false, hide node version if it's the same as global:
  # $(nodenv version-name) == $(nodenv global).
  typeset -g POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW=false
  # If set to false, hide node version if it's equal to "system".
  typeset -g POWERLEVEL9K_NODENV_SHOW_SYSTEM=false
```

**Comment by romkatv** [comment]
`node_version` is unrelated to `nodenv`. It's supposed to display the output of `node --version`. What does this command print? Also, what does `which node` print?

**Comment by fdsa789** [comment]
@romkatv 

Seem like there is node from homebrew and from nodenv.

```shell
$ node --version -> v19.7.0
$ which node -> /opt/homebrew/bin/node
```

 I removed node from homebrew and it's like this:

```shell
$ node --version -> v19.7.0
$ which node -> /Users/fdsa/.nodenv/shims/node
```

**Comment by romkatv** [comment]
Thanks for the info. I've fixed this bug. However, you probably don't want to use `node_version` in the first place. Try this:

1. Disable `node_version` prompt segment.
2. Enable `nodenv` prompt segment.
3. If you want the version to be shown even if it's the same as global, set `POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW=true`.
4. If you want the version to be shown only in directories with `package.json`, set `POWERLEVEL9K_NODENV_SHOW_ON_UPGLOB='package.json'`.

**Comment by fdsa789** [comment]
@romkatv Changed my config as below, but still not showing prompt. Thanks for the support.

```shell
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    background_jobs         # presence of background jobs
    direnv                  # direnv status (https://direnv.net/)
    asdf                    # asdf version manager (https://github.com/asdf-vm/asdf)
    virtualenv              # python virtual environment (https://docs.python.org/3/library/venv.html)
    anaconda                # conda environment (https://conda.io/)
    pyenv                   # python environment (https://github.com/pyenv/pyenv)
    goenv                   # go environment (https://github.com/syndbg/goenv)
    nodenv                  # node.js version from nodenv (https://github.com/nodenv/nodenv)
    # nvm                     # node.js version from nvm (https://github.com/nvm-sh/nvm)
    # nodeenv                 # node.js environment (https://github.com/ekalinin/nodeenv)
    # node_version          # node.js version
    go_version            # go version (https://golang.org)
    rust_version          # rustc version (https://www.rust-lang.org)
    # dotnet_version        # .NET version (https://dotnet.microsoft.com)
    # php_version           # php version (https://www.php.net/)
    # laravel_version       # laravel php framework version (https://laravel.com/)
    # java_version          # java version (https://www.java.com/)
    package               # name@version from package.json (https://docs.npmjs.com/files/package.json)
    rbenv                   # ruby version from rbenv (https://github.com/rbenv/rbenv)
    rvm                     # ruby version from rvm (https://rvm.io)
    fvm                     # flutter version management (https://github.com/leoafarias/fvm)
    luaenv                  # lua version from luaenv (https://github.com/cehoffman/luaenv)
    jenv                    # java version from jenv (https://github.com/jenv/jenv)
    plenv                   # perl version from plenv (https://github.com/tokuhirom/plenv)
    perlbrew                # perl version from perlbrew (https://github.com/gugod/App-perlbrew)
    phpenv                  # php version from phpenv (https://github.com/phpenv/phpenv)
    scalaenv                # scala version from scalaenv (https://github.com/scalaenv/scalaenv)
    haskell_stack           # haskell version from stack (https://haskellstack.org/)
    kubecontext             # current kubernetes context (https://kubernetes.io/)
    terraform               # terraform workspace (https://www.terraform.io)
    # terraform_version     # terraform version (https://www.terraform.io)
    aws                     # aws profile (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html)
    aws_eb_env              # aws elastic beanstalk environment (https://aws.amazon.com/elasticbeanstalk/)
    azure                   # azure account name (https://docs.microsoft.com/en-us/cli/azure)
    gcloud                  # google cloud cli account and project (https://cloud.google.com/)
    google_app_cred         # google application credentials (https://cloud.google.com/docs/authentication/production)
    toolbox                 # toolbox name (https://github.com/containers/toolbox)
    context                 # user@hostname
    nordvpn                 # nordvpn connection status, linux only (https://nordvpn.com/)
    ranger                  # ranger shell (https://github.com/ranger/ranger)
    nnn                     # nnn shell (https://github.com/jarun/nnn)
    lf                      # lf shell (https://github.com/gokcehan/lf)
    xplr                    # xplr shell (https://github.com/sayanarijit/xplr)
    vim_shell               # vim shell indicator (:sh)
    midnight_commander      # midnight commander shell (https://midnight-commander.org/)
    nix_shell               # nix shell (https://nixos.org/nixos/nix-pills/developing-with-nix-shell.html)
    # vi_mode               # vi mode (you don't need this if you've enabled prompt_char)
    # vpn_ip                # virtual private network indicator
    # load                  # CPU load
    # disk_usage            # disk usage
    # ram                   # free RAM
    # swap                  # used swap
    todo                    # todo items (https://github.com/todotxt/todo.txt-cli)
    timewarrior             # timewarrior tracking status (https://timewarrior.net/)
    taskwarrior             # taskwarrior task count (https://taskwarrior.org/)
    # cpu_arch              # CPU architecture
    time                    # current time
    # =========================[ Line #2 ]=========================
    newline
    # ip                    # ip address and bandwidth usage for a specified network interface
    # public_ip             # public IP address
    # proxy                 # system-wide http/https/ftp proxy
    # battery               # internal battery
    # wifi                  # wifi speed
    # example               # example user-defined segment (see prompt_example function below)
  )


# other configs here


  typeset -g POWERLEVEL9K_NODENV_FOREGROUND=2
  typeset -g POWERLEVEL9K_NODENV_BACKGROUND=0
  # Hide node version if it doesn't come from one of these sources.
  typeset -g POWERLEVEL9K_NODENV_SOURCES=(shell local global)
  # If set to false, hide node version if it's the same as global:
  # $(nodenv version-name) == $(nodenv global).
  typeset -g POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW=false
  # If set to false, hide node version if it's equal to "system".
  typeset -g POWERLEVEL9K_NODENV_SHOW_SYSTEM=true
  # https://github.com/romkatv/powerlevel10k/issues/2268
  typeset -g POWERLEVEL9K_NODENV_SHOW_ON_UPGLOB='package.json'
  # Custom icon.
  # typeset -g POWERLEVEL9K_NODENV_VISUAL_IDENTIFIER_EXPANSION='⭐'
```

![screenshot](https://user-images.githubusercontent.com/107389031/232752623-89c31be5-64a8-4918-bb46-b01722d67b05.png)

**Comment by romkatv** [comment]
Read my last comment carefully without skipping anything in it.

**Comment by fdsa789** [comment]
@romkatv Oh, my bad 😅 Thank you so much for your support, its fixed!

**Comment by romkatv** [comment]
You are welcome.

Thanks for reporting the issue.
