### ISSUE TITLE
_p9k_should_join_right:1: bad math expression: empty string 

### ISSUE THREAD

**Issue by mahmoudhossam** [romkatv/powerlevel10k#3]
I'm having a similar issue to #1 but the message is different.

I'm using [antigen](https://github.com/zsh-users/antigen) on Arch Linux and my ZSH version is `5.7.1`,  my `.zshrc` looks like this:

```shell
export ADOTDIR=$HOME/.antigen
export ANTIGEN_BUNDLES=$ADOTDIR/bundles
export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv dir vcs)
export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
export POWERLEVEL9K_STATUS_VERBOSE=false
export POWERLEVEL9K_MODE='nerdfont-complete'
export POWERLEVEL9K_PROMPT_ON_NEWLINE=true
export TERM="screen-256color"
export DISABLE_AUTO_TITLE="true"

# Use antigen
source $ADOTDIR/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

#zsh theme
antigen theme romkatv/powerlevel10k powerlevel10k
```

**Comment by romkatv** [comment]
Thanks for the report. This is now fixed. Please try again.

I've also verified that gitstatus works on Arch Linux. You can enable it with `antigen bundle romkatv/gitstatus` for extra performance improvement.

**Comment by mahmoudhossam** [comment]
@romkatv The issue still persists.

My full `.zshrc` can be found [here](https://github.com/mahmoudhossam/dotfiles/blob/1845bb3ffc32f571c763f61b28c26588ab1a17c6/.zshrc), hope this helps.

**Comment by romkatv** [comment]
@mahmoudhossam Is it possible that antigen hasn't picked up the latest version of Powerlevel10k? Please try to force refresh or something.

To ensure you have the latest version, check that your local romkatv/powerlevel10k/powerlevel10k.zsh-theme has [this return](https://github.com/romkatv/powerlevel10k/blob/eaa555c00f4f6f470dcab145479a8d2ea244230b/powerlevel9k.zsh-theme#L1495). And to be double sure this is the code that antigen loads, add `echo here >&2` at the beginning of `prompt_status` function in the same file. This message should be printed on every prompt.

FYI, here's how I tested my fix:

```zsh
docker run -e LANG=en_US.utf8 -e LC_ALL=en_US.utf8 -e TERM=$TERM -it --rm archlinux/base bash -c '
  set -ue
  pacman -Sy --noconfirm zsh git curl gawk
  mkdir ~/.antigen
  curl -L git.io/antigen >~/.antigen/antigen.zsh

  echo "
    export ADOTDIR=\$HOME/.antigen
    export ANTIGEN_BUNDLES=\$ADOTDIR/bundles
    export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv dir vcs)
    export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
    export POWERLEVEL9K_STATUS_VERBOSE=false
    export POWERLEVEL9K_MODE=nerdfont-complete
    export POWERLEVEL9K_PROMPT_ON_NEWLINE=true
    export TERM=screen-256color
    export TERMINAL=kitty
    export DISABLE_AUTO_TITLE=true

    source ~/.antigen/antigen.zsh

    antigen use oh-my-zsh
    antigen theme romkatv/powerlevel10k powerlevel10k
    antigen bundle git
    antigen bundle github
    antigen bundle colored-man-pages
    antigen bundle systemd
    antigen bundle archlinux
    antigen bundle command-not-found
    antigen bundle web-search
    antigen bundle zsh-users/zsh-syntax-highlighting
    antigen bundle zsh-users/zsh-completions
    antigen bundle zsh-users/zsh-autosuggestions
    antigen bundle fabric
    antigen bundle vagrant
    antigen bundle docker
    antigen bundle docker-compose
    antigen bundle virtualenv
    antigen bundle tmux
    antigen bundle git-extras

    # Disabled because it reports errors when loading.
    # It is probably unrelated to Powerlevel10k issues.
    # antigen bundle z

    antigen bundle StackExchange/blackbox
    antigen bundle zchee/go-zsh-completions
    antigen bundle romkatv/gitstatus
    antigen apply" >~/start

  echo "******************************"
  echo "Please type \"source ~/start\""
  echo "******************************"
  zsh -i
'
```

**Comment by romkatv** [comment]
Closing this issue as I believe it's fixed. Please reopen if not.
