### ISSUE TITLE
[ui] Background color change after running some commands

### ISSUE THREAD

**Issue by nashokin** [romkatv/powerlevel10k#326]
Hi, I've noticed that the left ending segment background color changes or not being set back after running some commands. Just wanted to flag this.

![2019-11-08](https://user-images.githubusercontent.com/6571738/68722421-7aa00080-0609-11ea-8a12-587f350d5424.png)

**Comment by romkatv** [comment]
Thanks for reporting this.

Is my understanding of what you've captured in the screenshot correct?

1. Ran `sudo apt update`.
2. Once the command has completed, `vcs` prompt segment (the one showing `master`) got rendered on grey background.
3. It stayed grey for a long time (over 30 minutes) and turned green only when ENTER was eventually pressed.

Expected: Whenever `vcs` is rendered on grey background, it turns green by itself after a short period of time.

Is this correct?

Are you using native Linux or WSL/VM?

**Comment by nashokin** [comment]
Yes, your understanding is correct. I was destructed, when I wanted to report this, so that's why there is 30 mins window. It also happens for me on other pc.

I'm using cmder, wsl and zsh on ubuntu. I can't see the pattern how to reproduce it consistently.

Below is a screenshot of this morning, when it happened on a different pc:

![2019-11-14 08_58_17](https://user-images.githubusercontent.com/6571738/68808328-9fee4680-06bd-11ea-9b51-a4ca8bee99fb.png)

**Comment by romkatv** [comment]
I think you are being affected by a bug in zsh that's been fixed in https://github.com/zsh-users/zsh/commit/5e11082349bf72897f93f3a4493a97a2caf15984. Could you try building zsh from HEAD and checking whether it fixes the problem?

Build zsh from HEAD and install it as `/usr/local/bin/zsh`:

```zsh
(
  emulate -L zsh
  setopt err_return
  sudo apt update
  sudo apt install -y git build-essential libncurses-dev gcc autoconf man yodl
  zsh_dir="$(mktemp -d)"
  {
    git clone https://github.com/zsh-users/zsh $zsh_dir
    cd $zsh_dir
    ./Util/preconfig
    ./configure
    sudo make -j 20 install
  } always {
    sudo rm -rf $zsh_dir
  }
)
```

(Your original `zsh` is still available as `/bin/zsh` and `/usr/bin/zsh`.)

Add `/usr/loca/bin/zsh` to the list of login shells:

```zsh
grep -qE '^/usr/local/bin/zsh$' /etc/shells || sudo tee -a /etc/shells <<</usr/local/bin/zsh >/dev/null
```

Make `/usr/local/bin/zsh` your login shell:

```zsh
chsh -s /usr/local/bin/zsh
```

**Comment by romkatv** [comment]
Closing due to inactivity. Please reopen if you can provide the information I've requested above.

**Comment by nashokin** [comment]
No worries. I've compiled the latest `zsh` from source, seems to run ok, wanted to keep an eye on it for a couple of days; so far so good. Although, the font issue is still happening even with you recommended fonts. Personally I don't think it has anything to do with `powerlevel10k` code, e.g. inbuilt Visual Studio Code terminal is able to display all glyphs correctly; it is something to do with `cmder` itself, I'm checking with them at the moment, but might re-open the font issue. Thank you for your support.

![2019-11-19](https://user-images.githubusercontent.com/6571738/69102037-63ec2480-0ab5-11ea-8c5b-600ce86a9956.png)

**Comment by romkatv** [comment]
> I've compiled the latest `zsh` from source, seems to run ok, wanted to keep an eye on it for a couple of days; so far so good.

Thanks for the confirmation. If this problem reappears, please ping this issue.

Just to clarify, it's normal for Git segment to turn grey for a short time. This tells you that Git status is being refreshed in the background and what you are seeing may be stale. What is not normal is for Git status to be stuck in this state.

> Although, the font issue is still happening even with you recommended fonts.

Do you mean the missing glyph on error? I wasn't aware that cmder cannot display ↵ (U+21B5) even when using a font that has the glyph. Thanks for letting me know.

I've replaced ↵ (U+21B5) with ✘ (U+2718) in config templates. If you update powerlevel10k to the latest version and run `p10k configure`, it should fix the issue for you.

**Comment by romkatv** [comment]
Looking closer at your screenshot I see that cmder is also unable to display `⇡` (U+21E1). If I saw this earlier I wouldn't have sent my previous commit. If missing glyphs in cmder bother you, please replace them manually by editing `~/.p10k.zsh`.

**Comment by nashokin** [comment]
Given the opportunity, can you advice how to change the background color of the left segment where the Ubuntu icon is? I want the color to be just for that segment and not to affect any other colors.

Also, this issue is still happening with the latest `zsh` build. Seems like I can replicate it just by hitting return rapidly, screenshot below, this is Visual Studio Code terminal.
![2019-11-20 VS Code](https://user-images.githubusercontent.com/6571738/69198025-720a7580-0b87-11ea-84f0-510a6d7f3617.png)

All glyphs display correctly in Visual Studio Code and Windows Terminal Preview. This screenshot is just for information, when switching to 9k theme it displays the arrow(s) correctly. I know it's a different arrow from what you have in your config, I just don't understand how `cmder` is failing to display the arrows defined in your configuration. I might edit the `.p10k.zsh` config, it just feels like not the right thing to do to fix it.
![2019-11-20](https://user-images.githubusercontent.com/6571738/69198136-d4637600-0b87-11ea-80fc-483b9e99f5da.png)

This is a minor glitch, I'll leave it up to you to re-open this issue, I don't know if this can be fixed with your code.

**Comment by romkatv** [comment]
> Given the opportunity, can you advice how to change the background color of the left segment where the Ubuntu icon is? I want the color to be just for that segment and not to affect any other colors.

Open `~/.p10k.zsh` and edit it. Search for `OS_ICON`.

Your config is a bit dated. Nowadays OS icon is black on white by default. If you update powerlevel10k and rerun `p10k configure`, you'll get the new default colors.

> Also, this issue is still happening with the latest `zsh` build. Seems like I can replicate it just by hitting return rapidly, screenshot below, this is Visual Studio Code terminal.

This is expected behavior. See my comment above where I explain what grey Git prompt means.

> I just don't understand how `cmder` is failing to display the arrows defined in your configuration.

Software has bugs. Cmder is software.

>  I might edit the `.p10k.zsh` config, it just feels like not the right thing to do to fix it.

There are other options if you don't feel like changing your config.

1. Try to figure out how to fix Cmder. I don't use it myself but a quick Google search shows that Cmder is based on ConEmu and in ConEmu there are configuration options that specify which fonts are used for different Unicode ranges. If you can tell it to use MesloLGS NF for all Unicode characters, it'll work. See https://github.com/Maximus5/ConEmu/issues/988. You might want to exclude Block Elements (from U+2580 to U+259F) as Cmder seems to have native support for them judging from your screenshot (this is why the fade effect looks better in Cmder than in VSCode). Maybe there is a special checkbox for it.
2. Cmder is open source. You can try fixing the bug yourself.
3. You can report the bug to Cmder and hope they fix it.
4. You can switch to a different terminal emulator.

**Comment by nashokin** [comment]
Thank you for your support. I think I've fixed it to the point it almost looks like on my Ubuntu laptop. 2 things still don't happen, it doesn't bold active directory in the path and color applied to the right end segment blends in with the background, but it's there.

I've already asked you a lot of questions, but if you have a spare minute, I'd appreciate a suggestion how to fix the above.

Also, how to calculate colors in the configuration, what's the name for that convention? I need to do some research how to convert it, I want the os icon background to be orange, same as on Ubuntu logo.

In case you have some one else trying to correct the issues I was having with `cmder` or `conemu`, there is a screenshot below of the font settings, I do have to use your font in the end to display special characters correctly, almost a must =)

![2019-11-21](https://user-images.githubusercontent.com/6571738/69305904-ca21a480-0c79-11ea-9151-9ddaeda086f3.png)

**Comment by romkatv** [comment]
> it doesn't bold active directory in the path

If you cannot configure your terminal to display bold differently from non-bold, you can try using a different color instead. The parameter's name is `POWERLEVEL9K_DIR_ANCHOR_FOREGROUND`.

> and color applied to the right end segment blends in with the background, but it's there.

Do you refer to black background being indistinguishable from transparent background?

```zsh
print -P '%K{0}black background%k transparent background'
```

You can either try to figure out how to fix your terminal or replace black background in `status` with something else.

```zsh
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=8
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=8
```

> Also, how to calculate colors in the configuration, what's the name for that convention?

I'm not sure what you are asking so I'll shoot in the general direction of your question.

In zsh you can use one of the preset 256 colors by specifying its decimal number.

```zsh
print -P '%F{2}this is green%f'
```

With p10k:

```zsh
typeset -g POWERLEVEL9K_DIR_BACKGROUND=2
```

The exact colors depend on your terminal. Here's how you can see them all:

```zsh
for i in {0..255}; do print -Pn "%${i}F${(l:3::0:)i}%f " ${${(M)$((i%8)):#7}:+$'\n'}; done  #colors
```

See that `#colors` at the end? That's technically a comment but we use it as a tag here. Any time you want to run that script, press `Ctrl-R` and type `#colors`. You'll see the last command "tagged" with `#colors`. This is handy for many things. Every time you find yourself typing the same or similar command more than once, tag it.

Want to use more than 256 colors? Use `#xxxxxx` notation to specify 24-bit colors, a.k.a. true color.

```zsh
print -P '%F{#00ff00}this is very green%f'
typeset -g POWERLEVEL9K_DIR_BACKGROUND='#00ff00'
```

Want an easier way to pick 24-bit colors? Google's got your back with their interactive color picker: https://www.google.com/search?q=pick+color. Choose the color you like and copy its HEX code.

> I need to do some research how to convert it, I want the os icon background to be orange, same as on Ubuntu logo.

Ubuntu orange is `#e95420`.

```zsh
POWERLEVEL9K_OS_ICON_BACKGROUND=`#e95420`
```

> In case you have some one else trying to correct the issues I was having with `cmder` or `conemu`, there is a screenshot below of the font settings, I do have to use your font in the end to display special characters correctly, almost a must =)
> 
> ![2019-11-21](https://user-images.githubusercontent.com/6571738/69305904-ca21a480-0c79-11ea-9151-9ddaeda086f3.png)

That's quite some dedication to Ubuntu Mono. I don't know many users who prefer it to over Meslo.

**Comment by nashokin** [comment]
Don't get me wrong, I was a huge fan of [Meslo-Font](https://github.com/andreberg/Meslo-Font) almost since it's inception. This was the font I've been using for more that half a decade.

Can I ask you where did you get you recommended fonts? It seems like it's downloading from your repository directly, but I assume it's the same as these fonts: [Meslo Nerd Fonts](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Meslo)

If this is correct, it means that Ubuntu fonts are not patched correctly. Or have you patched your fonts yourself?

**Comment by romkatv** [comment]
> Can I ask you where did you get you recommended fonts?

I patched Meslo using modified scripts from nerdfonts. Then I hand-edited the resulting font in font-forge.There was a lot of manual work that I unfortunately cannot reproduce. I did it for myself (hence the font is in my dotfiles repo) but then listed the font as recommended for p10k because many (many!) users are having difficulties installing a font that works. My font works everywhere and looks great, so it gives p10k users a good starting point.

**Comment by nashokin** [comment]
Thank you for your honest answer. This seems like you're locking users to your specific font in order to display special glyphs, it doesn't work in `cmder` (also tested with `conemu`) with `nerd-fonts` specified, your special font must be used as an Alternative font for Pseudographics.

I don't want to express any negativity here, you've done a great job with `powerlevel10k`. The README is misleading in this case; potentially you might loose some audience, when people figure out what's going on.

Also, I've tested it on my Linux laptop, it works and looks great.

**Comment by romkatv** [comment]
> Thank you for your honest answer. This seems like you're locking users to your specific font in order to display special glyphs

This is not true. The recommended font doesn't have any extra glyphs compared to any correctly-patched nerd font. Powerlevel10k doesn't use any unicode code points that are not found in correctly-patched nerd fonts. The manual edits that I've applied are just size changes for some glyphs (primarily block glyphs, which aren't even used by cmder).

> it doesn't work in `cmder` (also tested with `conemu`) with `nerd-fonts` specified

If I understand you correctly, you are saying that when you use some specific font from Nerd Fonts in `cmder`, the terminal is unable to display a glyph that is indeed found in the font. For example, `echo '\u21B5'` prints a missing-glyph box rather than https://www.compart.com/en/unicode/U+21B5. If this is the case and you believe this is not a user error, please open an issue against nerd fonts and/or cmder. 

> your special font must be used as an Alternative font for Pseudographics.

As I mentioned above, the recommended font is not special. It's simply a correctly-patched nerd font with correctly sized block glyphs. It doesn't have any extra glyphs compared to any other correctly-patched nerd font. You can use any correctly-patched nerd font in place of it. If the recommended font works, another correctly-patched nerd font will work, too.

> The README is misleading in this case

Which part?

> potentially you might loose some audience, when people figure out what's going on.

There is nothing "going on".
